[pytest]
testpaths = tests
norecursedirs = .venv .git AppData Local Microsoft Windows
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*pin_memory.*:UserWarning

addopts = --tracing=retain-on-failure --alluredir=allure-results